baseURL = 'https://e.tome.github.io/blog-site.github.io/'
languageCode = 'en-us'
title = 'very cool blog'
theme = 'diary'
relativeURLs = true
canonifyURLs = true

[sitemap]
  changefreq = "always"
  filename = "sitemap.xml"
  priority = 0.5

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
enableGitalk = false

  [[params.social]]
    name = "github"
    icon = "fab fa-github"
    url = "https://github.com/E-Tome"
    weight = 1

  [[params.social]]
    name = "linkedin"
    icon = "fab fa-linkedin"
    url = "https://www.linkedin.com/in/edvard-tome-400957245/"
    weight = 2

  [[params.social]]
    name = "instagram"
    icon = "fab fa-instagram"
    url = "https://www.instagram.com/e.tome_/"
    weight = 3

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
